// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace webshop.api.Migrations
{
    [DbContext(typeof(WebshopContext))]
    [Migration("20260307063536_ProductAddMaxLength")]
    partial class ProductAddMaxLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Resistors"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Capacitors"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inductors"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Semiconductors"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Microcontrollers"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Power"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Connectors"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sensors"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Displays"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Passive Components"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 9
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 9
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 10
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 10
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 11
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 11
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 12
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 12
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 13
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 13
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 14
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 15
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 16
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 17
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 18
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 19
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 20
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 21
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 22
                        },
                        new
                        {
                            CategoriesId = 10,
                            ProductsId = 22
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 23
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 24
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 25
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 25
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 26
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 27
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 28
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 29
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 29
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 30
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 30
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 31
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 31
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 32
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 33
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 34
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 35
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 35
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 36
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 37
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 38
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 39
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 40
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 41
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 42
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 43
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 44
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 45
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 46
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 47
                        },
                        new
                        {
                            CategoriesId = 9,
                            ProductsId = 48
                        },
                        new
                        {
                            CategoriesId = 9,
                            ProductsId = 49
                        },
                        new
                        {
                            CategoriesId = 9,
                            ProductsId = 50
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 50
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SvgType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General purpose 1kΩ through-hole resistor",
                            Name = "1kΩ Resistor",
                            Price = 1m,
                            Stock = 500,
                            SvgType = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "General purpose 4.7kΩ through-hole resistor",
                            Name = "4.7kΩ Resistor",
                            Price = 1m,
                            Stock = 500,
                            SvgType = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Common LED current limiting resistor",
                            Name = "220Ω Resistor",
                            Price = 1m,
                            Stock = 500,
                            SvgType = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "High resistance through-hole resistor",
                            Name = "1MΩ Resistor",
                            Price = 1m,
                            Stock = 300,
                            SvgType = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Adjustable rotary resistor",
                            Name = "10kΩ Potentiometer",
                            Price = 15m,
                            Stock = 150,
                            SvgType = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Large electrolytic capacitor 25V",
                            Name = "470µF Electrolytic Capacitor",
                            Price = 5m,
                            Stock = 200,
                            SvgType = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Polyester film capacitor",
                            Name = "1µF Film Capacitor",
                            Price = 3m,
                            Stock = 200,
                            SvgType = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Small ceramic capacitor for oscillators",
                            Name = "22pF Ceramic Capacitor",
                            Price = 2m,
                            Stock = 400,
                            SvgType = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Decoupling capacitor for power lines",
                            Name = "0.1µF Bypass Capacitor",
                            Price = 2m,
                            Stock = 400,
                            SvgType = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Large smoothing capacitor 16V",
                            Name = "1000µF Electrolytic Capacitor",
                            Price = 6m,
                            Stock = 150,
                            SvgType = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Small signal inductor",
                            Name = "100µH Inductor",
                            Price = 5m,
                            Stock = 200,
                            SvgType = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Through-hole power inductor",
                            Name = "1mH Inductor",
                            Price = 8m,
                            Stock = 150,
                            SvgType = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Surface mount inductor for compact designs",
                            Name = "47µH SMD Inductor",
                            Price = 9m,
                            Stock = 100,
                            SvgType = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "5mm blue LED 3.2V forward voltage",
                            Name = "Blue LED",
                            Price = 2m,
                            Stock = 300,
                            SvgType = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "5mm green LED 2.1V forward voltage",
                            Name = "Green LED",
                            Price = 2m,
                            Stock = 300,
                            SvgType = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "5mm common cathode RGB LED",
                            Name = "RGB LED",
                            Price = 5m,
                            Stock = 200,
                            SvgType = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Infrared LED 940nm for remote control",
                            Name = "IR LED",
                            Price = 3m,
                            Stock = 200,
                            SvgType = 3
                        },
                        new
                        {
                            Id = 18,
                            Description = "General purpose PNP transistor",
                            Name = "PNP Transistor BC557",
                            Price = 3m,
                            Stock = 200,
                            SvgType = 4
                        },
                        new
                        {
                            Id = 19,
                            Description = "N-channel power MOSFET",
                            Name = "MOSFET IRF540N",
                            Price = 15m,
                            Stock = 100,
                            SvgType = 4
                        },
                        new
                        {
                            Id = 20,
                            Description = "General purpose rectifier diode",
                            Name = "1N4007 Diode",
                            Price = 2m,
                            Stock = 400,
                            SvgType = 11
                        },
                        new
                        {
                            Id = 21,
                            Description = "5.1V voltage reference zener diode",
                            Name = "Zener Diode 5.1V",
                            Price = 2m,
                            Stock = 300,
                            SvgType = 11
                        },
                        new
                        {
                            Id = 22,
                            Description = "Classic 555 timer integrated circuit",
                            Name = "NE555 Timer IC",
                            Price = 6m,
                            Stock = 200,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 23,
                            Description = "Dual operational amplifier IC",
                            Name = "LM358 Op-Amp",
                            Price = 8m,
                            Stock = 150,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "8-bit serial to parallel shift register",
                            Name = "74HC595 Shift Register",
                            Price = 9m,
                            Stock = 150,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 25,
                            Description = "8-bit AVR microcontroller in DIP-8 package",
                            Name = "ATtiny85",
                            Price = 25m,
                            Stock = 75,
                            SvgType = 6
                        },
                        new
                        {
                            Id = 26,
                            Description = "Compact Arduino board with ATmega328P",
                            Name = "Arduino Nano",
                            Price = 89m,
                            Stock = 50,
                            SvgType = 6
                        },
                        new
                        {
                            Id = 27,
                            Description = "Arduino board with ATmega2560, 54 I/O pins",
                            Name = "Arduino Mega",
                            Price = 189m,
                            Stock = 30,
                            SvgType = 6
                        },
                        new
                        {
                            Id = 28,
                            Description = "STM32F103 ARM Cortex-M3 development board",
                            Name = "STM32 Blue Pill",
                            Price = 49m,
                            Stock = 40,
                            SvgType = 6
                        },
                        new
                        {
                            Id = 29,
                            Description = "WiFi enabled microcontroller board",
                            Name = "ESP8266 NodeMCU",
                            Price = 59m,
                            Stock = 60,
                            SvgType = 6
                        },
                        new
                        {
                            Id = 30,
                            Description = "Adjustable positive voltage regulator",
                            Name = "LM317 Voltage Regulator",
                            Price = 9m,
                            Stock = 150,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 31,
                            Description = "12V fixed positive voltage regulator",
                            Name = "LM7812 Voltage Regulator",
                            Price = 9m,
                            Stock = 150,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 32,
                            Description = "TP4056 single cell LiPo charger",
                            Name = "LiPo Charger Module",
                            Price = 19m,
                            Stock = 80,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 33,
                            Description = "MT3608 boost converter module 2-24V",
                            Name = "Step-Up Boost Converter",
                            Price = 25m,
                            Stock = 60,
                            SvgType = 5
                        },
                        new
                        {
                            Id = 34,
                            Description = "4xAA battery holder with switch",
                            Name = "AA Battery Holder 4x",
                            Price = 15m,
                            Stock = 100,
                            SvgType = 8
                        },
                        new
                        {
                            Id = 35,
                            Description = "9V battery snap connector leads",
                            Name = "9V Battery Snap",
                            Price = 5m,
                            Stock = 150,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 36,
                            Description = "2.54mm pitch breakaway pin headers",
                            Name = "Male Pin Headers 40-pin",
                            Price = 6m,
                            Stock = 300,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 37,
                            Description = "2.54mm pitch female pin headers",
                            Name = "Female Pin Headers 40-pin",
                            Price = 7m,
                            Stock = 300,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 38,
                            Description = "Standard USB cable for Arduino",
                            Name = "USB-A to USB-B Cable",
                            Price = 29m,
                            Stock = 100,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 39,
                            Description = "Micro USB data and charging cable",
                            Name = "Micro USB Cable",
                            Price = 25m,
                            Stock = 100,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 40,
                            Description = "2.54mm pitch PCB screw terminal",
                            Name = "Screw Terminal 2-pin",
                            Price = 4m,
                            Stock = 200,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 41,
                            Description = "2.54mm pitch PCB screw terminal",
                            Name = "Screw Terminal 3-pin",
                            Price = 5m,
                            Stock = 200,
                            SvgType = 7
                        },
                        new
                        {
                            Id = 42,
                            Description = "Analog and digital soil moisture detection",
                            Name = "Soil Moisture Sensor",
                            Price = 29m,
                            Stock = 60,
                            SvgType = 9
                        },
                        new
                        {
                            Id = 43,
                            Description = "Microphone sound detection module",
                            Name = "Sound Sensor Module",
                            Price = 25m,
                            Stock = 60,
                            SvgType = 9
                        },
                        new
                        {
                            Id = 44,
                            Description = "IR flame detection sensor",
                            Name = "Flame Sensor Module",
                            Price = 19m,
                            Stock = 60,
                            SvgType = 9
                        },
                        new
                        {
                            Id = 45,
                            Description = "Flammable gas and smoke sensor",
                            Name = "Gas Sensor MQ-2",
                            Price = 35m,
                            Stock = 50,
                            SvgType = 9
                        },
                        new
                        {
                            Id = 46,
                            Description = "6-axis accelerometer and gyroscope",
                            Name = "Gyroscope MPU-6050",
                            Price = 49m,
                            Stock = 40,
                            SvgType = 9
                        },
                        new
                        {
                            Id = 47,
                            Description = "I2C pressure and temperature sensor",
                            Name = "Barometric Pressure Sensor BMP280",
                            Price = 39m,
                            Stock = 50,
                            SvgType = 9
                        },
                        new
                        {
                            Id = 48,
                            Description = "128x160 color TFT display SPI",
                            Name = "TFT LCD 1.8\"",
                            Price = 69m,
                            Stock = 40,
                            SvgType = 10
                        },
                        new
                        {
                            Id = 49,
                            Description = "296x128 e-ink display module",
                            Name = "E-Paper Display 2.9\"",
                            Price = 149m,
                            Stock = 20,
                            SvgType = 10
                        },
                        new
                        {
                            Id = 50,
                            Description = "MAX7219 8x8 LED dot matrix module",
                            Name = "LED Matrix 8x8",
                            Price = 39m,
                            Stock = 60,
                            SvgType = 10
                        });
                });

            modelBuilder.Entity("Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLineOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin.one@cgitest.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$1ZgH7ZYnidiR1zyqQJvDk.r6jSHmNuzhkyxLnS.ZksKjtcVTBy8C."
                        },
                        new
                        {
                            Id = 2,
                            Email = "not.admin@cgitest.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$VGTUMhLNxvxZO0FdSIGh3eYiiWeRW0HYYOG.7wdT49X2nDwMHtWyS"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shipping", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithOne("Shipping")
                        .HasForeignKey("Shipping", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
